### ISSUE TITLE
Markbot Issue

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/arrrgenes-treasure-tours#1]
Hi @muxlowc,

I'm encountering two issues with my html in Markbot, and I'm unsure of what I have to change to make these corrections (please see attached Markbot screenshot). 

The first issue is regarding landmarks, I've tried adding <id> tags to items to link them together and it doesn't seem to be working. Additionally, for the second problem regarding contrast in the banner I've tried changing both the background and the font colour but neither seems to be fixing that issue. 

Any guidance would be greatly appreciated!

Thanks,
Rianna

<img width="500" alt="Screen Shot 2020-04-01 at 1 13 09 PM" src="https://user-images.githubusercontent.com/55094049/78166600-0b417680-741b-11ea-9e2e-cf407af9d7d5.png">

**Comment by muxlowc** [comment]
@riannazandbelt 

okay so a few things:

1) what you have is technically correct, but markbot only wants you to have 2 skip-links (main / nav), so remove your "specs" skip-link and it's corresponding ID tag. 
You will also need to put your 
`<section tabindex="0" class="island">` inside of your `<main>` so that it's included inside of a "role="

I'll get you started here with the basic layout (I was playing around with your code and forgot exactly what I did haha)
```
<main>
  <section class="banner embed embed-16by9">
    <img>
    <div class="banner-content pin-c w-1 max-length gutter text-center">
      <h2>
      <p>
      <a>
...
  <div class="island">
    <section class="card embed embed-golden" tabindex="0" class="island">
      <div  class="card-content pin-c w-1 max-length gutter text-center">
        <i>
        <h2>
        <p>
        <a>
......
```

2) Remove your alt tag descriptions on your images for this assignment, and add role="presentation" for all imgs

3) You're going to have to add a background colour to your .banner in your css

Hope that helps!
